config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users

  resources :toys do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index destroy]
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos

  def photos=(attachables)
    attachables = Array(attachables).compact_blank

   if attachables.any?
     attachment_changes["photos"] =
       ActiveStorage::Attached::Changes::CreateMany.new("photos", self, photos.blobs + attachables)
   end
 end

  validates :name, :description, :price, presence: true
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @user_toys = Toy.where(user: current_user)
    @toy = Toy.new
    @toy.user = current_user
  end

  def show
    @toy = Toy.find(params[:id])
    @booking = Booking.new
    @booking.user = current_user
    @booking.toy = @toy
  end

  def new
    @toy = Toy.new
    @toy.user = current_user
  end

  def create
    @toy = Toy.new(toy_params)
    @toy.user = current_user
    if @toy.save
      redirect_to toy_path(@toy)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])
    @toy.photos.attach(params[:photos])
    if @toy.update(toy_params)
      redirect_to toy_path(@toy)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.destroy

    redirect_to toys_path, status: :see_other
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :price, photos: [])
  end
end

app/views/toys/edit.html.erb
<h1>Update your Toy</h1>

<%= simple_form_for @toy do |f| %>
  <%= f.input :name, label: 'Toy Name', error: 'Toy Name is mandatory, please specify one' %>
  <%= f.input :description, label: 'Toy Description' %>
  <%= f.input :price, label: 'Price' %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit %>
<% end %>

app/views/toys/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(250,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.freepik.com/premium-photo/warm-orange-purple-grunge-background-with-cement-faint-texture-marble-gradient_28629-604.jpg)">
  Here are your toys!
</div>

<div class='container'>
  <div class="cards">
    <div class="card-trip">
      <button style='width:100%; height:100%;'>
        <div class="card-trip-infos" style='background-image: linear-gradient(rgba(250,0,0,0.3), rgba(0,0,0,0.3)), url(https://media1.popsugar-assets.com/files/thumbor/K2kx6kiAGwERcN0wbV3Q3R3Jcfo/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2022/09/16/781/n/24155406/1b81d14b1f6afd02_netimg7eZaNT/i/best-new-toys-2021.jpg); background-size: cover; width:100%; height:100%;' data-bs-toggle="modal" data-bs-target="#newToy">
          <div style='text-align: center; margin: auto 0; width:100%;'>
            <h1>Create a New Toy</h1>
          </div>
        </div>
      </button>

      <div class="modal fade" id="newToy" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Create a new toy</h5>
            </div>

            <div>
              <div style="width:250px;text-align: center;margin:0 auto">
                <%= simple_form_for [@toy] do |f| %>
                  <%= f.input :name, label: 'Toy Name', error: 'Toy Name is mandatory, please specify one' %>
                  <%= f.input :description, label: 'Toy Description' %>
                  <%= f.input :price, label: 'Price' %>
                  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
                  <%= f.button :submit %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% @user_toys.each do |toy| %>
      <div class="card-trip">
      <% if toy.photos.first.nil? %>
        <%= image_tag 'placeholder.png', crop: :fill %>
      <% else %>
        <%= cl_image_tag toy.photos.first.key, crop: :fill %>
      <% end %>

        <div class="card-trip-infos">
          <div>
            <h2><%= link_to toy.name, toy_path(toy) %></h2>
            <% if toy.listed %>
              <p><%= '✅ This toy is listed for bookings.' %></p>
            <% end %>
          </div>

          <%#= link_to image_tag("delete.jpg"), toy_path(toy), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "card-trip-user avatar-bordered" %>

          <a data-turbo-method="delete" data-turbo-confirm="Are you sure?" href='<%= toy_path(toy)%>'><img src="https://p7.hiclipart.com/preview/833/287/785/check-mark-international-red-cross-and-red-crescent-movement-american-red-cross-clip-art-red-cross-mark-download-png.jpg" class="card-trip-user avatar-bordered" ></a>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/toys/new.html.erb
<div class='container'>
  <h1>Create a New Toy</h1>

  <%= simple_form_for @toy do |f| %>
    <%= f.input :name, label: 'Toy Name', error: 'Toy Name is mandatory, please specify one' %>
    <%= f.input :description, label: 'Toy Description' %>
    <%= f.input :price, label: 'Price' %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/toys/show.html.erb
<%# @toy.photos.each do |photo| %>
    <%#= cl_image_tag photo.key, crop: :thumb %>
<%# end %>
<%#= @toy.name %>
<%#= link_to "Delete Toy", toy_path(@toy), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<div class='container d-flex toy-container'>
  <%# <% @toy.photos.each do |photo| %>
    <%# <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <%# <% end %>

  <div id="toyCarousel" class="carousel slide m-5" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#toyCarousel" data-slide-to="0" class="active"></li>
      <% (@toy.photos.length-1).times do |i| %>
        <li data-target="#toyCarousel" data-slide-to=<%=i+1%>></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% @toy.photos.each_with_index do |photo, i| %>
          <div class="<%= i > 0 ? "carousel-item" : "carousel-item active" %>">
            <%= cl_image_tag photo.key, width: 600, crop: :fill, class: "carousel-image d-block w-100"%>
          </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#toyCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#toyCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="m-5">
      <h1><%= @toy.name %></h1>

      <div class="toy-details">
        <p><%= @toy.description %></p>
      </div>
      <div class="toy-options">
        <div>
          <p>
            <% if @toy.listed %>
              <%= "Available for "%>
              <span class="toy-price"><%= sprintf('%.2f',@toy.price.round(2)) %></span>
            <% else %>
              <%= "Not available 😔 "%>
            <% end %>
          </p>
        </div>

        <div>
          <% unless current_user.toys.where(id: params[:id]).empty? %>
            <%= link_to "Delete Toy", toy_path(@toy), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat toy-buttons" %>
            <%#= link_to "Update Toy", edit_toy_path(@toy), class: "btn btn-flat toy-buttons" %>
          <% end %>
          <% if @toy.user == current_user %>
            <button type="button" class="btn btn-flat toy-buttons" data-bs-toggle="modal" data-bs-target="#updateToy">
              Update Toy
            </button>

          <% else %>

          <button type="button" class="btn btn-flat toy-buttons" data-bs-toggle="modal" data-bs-target="#newBooking">
            Book now!
          </button>
          <% end %>
          <div class="modal fade" id="newBooking" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h3 class="modal-title"><%= "You're about to book:" %></h3>
                  <h3><%= "#{@toy.name}" %><h3>

                </div>

                <div style="text-align: center">
                  <br>
                  <h5><%= "Please pick the dates." %></h5>
                  <div style="width:250px;text-align: center;margin: 0 auto">
                    <%= simple_form_for [@toy, @booking] do |f| %>
                      <%= f.input :start_date, label: 'Start Date', html5: true %>
                      <%= f.input :end_date, label: 'End Date', html5: true %>
                      <%= f.button :submit %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="modal fade" id="updateToy" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h3 class="modal-title"><%= "You're about to book:" %></h3>
                  <h3><%= "#{@toy.name}" %><h3>

                  </button>
                </div>

                <div style="text-align: center">
                  <br>
                  <h5><%= "Update your toy." %></h5>
                  <div style="width:250px;text-align: center;margin: 0 auto">


                    <%= simple_form_for @toy do |f| %>
                      <%= f.input :name, label: 'Toy Name', error: 'Toy Name is mandatory, please specify one' %>
                      <%= f.input :description, label: 'Toy Description' %>
                      <%= f.input :price, label: 'Price' %>
                      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
                      <%= f.button :submit %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
  </div>
</div>