config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users

  resources :toys do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :toy

  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  validates :start_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @user_bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
    @toy = Toy.find(params[:toy_id])
    @booking.user = current_user
    @booking.toy = @toy
  end

  def create
    @booking = Booking.new(booking_params)
    @toy = Toy.find(params[:toy_id])
    @booking.user = current_user
    @booking.toy = @toy
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:toy_rating, :user_rating, :toy_review, :user_review, :start_date, :end_date)
  end
end

app/views/bookings/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(250,0,0,0.3), rgba(0,0,0,0.3)), url(https://img.freepik.com/premium-photo/warm-orange-purple-grunge-background-with-cement-faint-texture-marble-gradient_28629-604.jpg)">
  You've booked the following toys. Have fun!
</div>

<div class='container'>
  <div class="cards" id='all-toys'>
    <% @user_bookings.each do |booking| %>
      <div class="card-trip">
        <% booking.toy.photos.each do |photo| %>
          <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to booking.toy.name, toy_path(booking.toy) %></h2>
            <p>Between <%= booking.start_date %> and <%= booking.end_date %></p>
            <%# <a href=#>🗑️ Cancel this booking</a> %>
            <%# raise %>
            <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <img src="https://p7.hiclipart.com/preview/833/287/785/check-mark-international-red-cross-and-red-crescent-movement-american-red-cross-clip-art-red-cross-mark-download-png.jpg" class="card-trip-user avatar-bordered"/>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class='container'>
  <h1><%= "You're about to book #{@toy.name}" %></h1>

  <%= simple_form_for [@toy, @booking] do |f| %>
    <%= f.input :start_date, label: 'Start Date', html5: true %>
    <%= f.input :end_date, label: 'End Date', html5: true %>
    <%= f.button :submit %>
  <% end %>

</div>