config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users

  resources :toys do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[index destroy]
end

app/views/pages/home.html.erb
<%# <ul> %>
  <%# @available_toys.each do |toy| %>
    <%# <li> %>
      <%#= link_to toy.name, toy_path(toy) %>
      <%#= toy.description %>
      <%#= toy.price %>
      <%#= toy.listed %>
      <%#= toy.user.email %>
      <%#= link_to "Book", new_toy_booking_path(toy) %>
    <%# </li> %>
<%# </ul> %>

<%# <%= link_to "Write a story", "#", class: "btn btn-ghost" %>
<%# <%= link_to "Book now", "#", class: "btn btn-flat" %>
<%# <%= link_to "Start now", "#", class: "btn btn-gradient" %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(banner-background.jpg);">
  <div class="container" id="logo"  >
    Toys 4 Us
  </div>
  <div class="container">
    <h1>
      <% if user_signed_in? %>
        Hi <%= current_user.name %>!
      <% end %>
      Are you <strong>sad</strong> and <strong>lonely</strong>?
    </h1>
    <p>Try renting one of our toys so that you don't feel it!</p>
    <a class="btn btn-flat" href="#all-toys">Show all toys</a>
    <br>
    <br>
    <div class='disc'>
      <p>Disclaimer: Our toys will not make you less sad and lonely. Feelings of a less sad and lonely existence for a short while due to emotions induced by playing with Toys4Us toys shall not imply that Hellscape Enterprises, the parent company of Toys4Us, will be the holder of legal liability. Looking at this page for more than 1 second will be registered as consent that you are hereby and herewith accepting full responsibility. This is hereby 100% legally binding. And herewith.</p>
    </div>
  </div>
</div>

<div class='container'>
  <div class="cards" id='all-toys'>
    <% @available_toys.each do |toy| %>
      <div class="card-trip">

        <% toy.photos.each do |photo| %>
          <%= link_to toy_path(toy) do %>
            <%= cl_image_tag photo.key, crop: :fill %>
          <% end %>
        <% end %>
        <div class="card-trip-infos">
          <div style="width: 70%;">
            <h2><%= link_to toy.name, toy_path(toy) %></h2>
            <p style="overflow-wrap: break-word;"><%= toy.description %></p>
          </div>
          <div>
            <h2 class="card-trip-pricing">$ <%= sprintf('%.2f',toy.price.round(2)) %></h2>
          </div>
          <img src="https://i.stack.imgur.com/RoPPo.jpg" class="card-trip-user avatar-bordered" />
        </div>
      </div>
      <% end %>
  </div>
</div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>